### ISSUE TITLE
Path management buttons stopped working

### ISSUE THREAD

**Issue by Hufschmidt** [davidsev/owlbear-bendy-ruler#1]
First of, thanks for this awesome extension. It has made my live so much easier. :D

It looks like the checkmark and trash-bin icons stopped working with owlbear 2.3 for some reason as does right-click to cancel tool usage.

Side-Note: It would be cool if we could use enter/return key to finalize a path, just like esc deletes it.

**Comment by davidsev** [comment]
Hi, thanks for the report.

The buttons are fixed now, and I've added support for Enter to finish the path.
Right click to cancel sitll doesn't work, I've made a bug report to the OBR devs but there's nothing I can do about it for now.
